apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ns-app
  template:
    metadata:
      labels:
        app: ns-app
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        storage: ssd          # node must have exactly this label
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "sleep 3600"]