apiVersion: v1
kind: ResourceQuota
metadata:
  name: notterminating-quota
  namespace: quota-demo
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "8Gi"
  scopeSelector:
    matchExpressions:
      - scopeName: NotTerminating
        operator: Exists
