apiVersion: v1
kind: ResourceQuota
metadata:
  name: critical-quota
  namespace: quota-demo
spec:
  hard:
    pods: "2"
    requests.cpu: "2"
    requests.memory: "2Gi"
  scopeSelector:
    matchExpressions:
      - scopeName: PriorityClass
        operator: In
        values:
          - critical
