apiVersion: v1
kind: Pod
metadata:
  name: non-preempting-pod
spec:
  terminationGracePeriodSeconds: 0
  priorityClassName: high-non-preempting
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      resources:
        requests:
          cpu: "3000m"
          memory: "3Gi"
        limits:
          cpu: "3000m"
          memory: "3Gi"
