apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-affinity-required
spec:
  selector:
    matchLabels:
      app: ds-affinity-required
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ds-affinity-required
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role
                    operator: In
                    values:
                      - worker
                      - compute          # Node must have node-role=worker OR node-role=compute
                  - key: env
                    operator: NotIn
                    values:
                      - dev              # AND node must NOT have env=dev
      containers:
        - name: nginx
          image: nginx:1.27
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
