apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unhealthy-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: unhealthy-test
  unhealthyPodEvictionPolicy: AlwaysAllow
