apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread-multi-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spread-multi
  template:
    metadata:
      labels:
        app: spread-multi
    spec:
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              app: spread-multi
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              app: spread-multi
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "sleep 3600"]