apiVersion: v1
kind: Service
metadata:
  name: external-db-svc
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: external-db-svc-endpoints
  labels:
    kubernetes.io/service-name: external-db-svc
addressType: IPv4
protocol: TCP
ports:
  - port: 5432
    protocol: TCP
endpoints:
  - addresses:
      - "10.240.0.50"    # IP of external database server
    conditions:
      ready: true
