apiVersion: v1
kind: ResourceQuota
metadata:
  name: critical-pods-only
  namespace: quota-demo
spec:
  hard:
    pods: "2"
  scopeSelector:
    matchExpressions:
    - scopeName: PriorityClass
      operator: In
      values: ["critical"]
