apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: quota-demo
spec:
  hard:
    pods: "10"
    services: "5"
    persistentvolumeclaims: "4"
    secrets: "10"
    configmaps: "10"
    services.loadbalancers: "0"
    services.nodeports: "0"
