apiVersion: v1
kind: ResourceQuota
metadata:
  name: besteffort-quota
  namespace: quota-demo
spec:
  hard:
    pods: "3"
  scopeSelector:
    matchExpressions:
      - scopeName: BestEffort
        operator: Exists
