apiVersion: apps/v1
kind: Deployment
metadata:
  name: spread-sa-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spread-sa
  template:
    metadata:
      labels:
        app: spread-sa
    spec:
      terminationGracePeriodSeconds: 0
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              app: spread-sa
      containers:
        - name: app
          image: busybox
          command: ["sh", "-c", "sleep 3600"]