apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  terminationGracePeriodSeconds: 0
  containers:
    - name: load
      image: busybox
      command:
        - sh
        - -c
        - |
          while true; do
            wget -q -O- http://nginx-svc
            done
